### ISSUE TITLE
AMIE causes IDA crash

### ISSUE THREAD

**Issue by RobertBuhren** [NeatMonster/AMIE#1]
Hi,
thanks for the awesome plugin. Unfortunately it has some rather weird side effects.
When this plugin is installed, opening the "Compiler" window (Options -> Compiler) causes an IDA crash.
If I remove this plugin, the crash is gone.
Version 7.2.181105 Linux x86_64 (32-bit address size)

Regards,
Robert

PS: I reported this issue also to hex-rays

**Comment by NeatMonster** [comment]
I investigated this issue a bit. It is indeed an unfortunate consequence of the fact that AMIE is using the `ida_idp.IDP_Hooks` class. This class appears to have an issue in the latest release of IDA.

Starting with a fresh instance of IDA 7.2 on Linux, opening a database and copy-pasting the following code in the Python console causes IDA to crash when opening the "Compiler" window.

```python
import ida_idp


class Test(ida_idp.IDP_Hooks):
   pass

test = Test()
test.hook()
```

I'm afraid there isn't much that I can do to fix this issue as using this class is the recommended way to listen to processor events. If the Hex-Rays support offers some workaround, please share it with me.

**Comment by NeatMonster** [comment]
I contacted Hex-Rays support. Here is the reply I got:

> Yes, it's an issue in IDAPython on Linux. AFAIK it only occurs when
going to that dialog, so the workaround is to not open it when any such
script is active. If necessary, we can provide you an IDAPython source
patch or a new fixed build.

As this isn't an issue with AMIE itself, I'm closing the issue as invalid. Feel free to reopen it if need be.
