### ISSUE TITLE
is this project dead ?

### ISSUE THREAD

**Issue by dummys** [NeatMonster/AMIE#10]
Hello,

I'm thinking of porting this plugins to be compatible to IDA 8.2. Do you still maintain the project or it is dead ?

**Comment by NeatMonster** [comment]
@dummys Sorry for the late reply. I'm no longer actively maintaining this project. So feel free to send a PR with the fixes needed for IDA 8.2, or even to fork the project. By the way, I've also added a license file (MIT) to the repository.

My original plan was to cleanup/rewrite the terrible [parser script](https://gist.github.com/NeatMonster/87ec0ffb48a604865bdc42fc2384bc48) used to generate the data files, and keep it up to date with the latest exploration tools, but I don't see that happening any time soon. While I'm at it, I also planned to release a [parsing script](https://gist.github.com/NeatMonster/363f1de319f6cfa3eac26d4fc3503f33) and corresponding [data files](https://gist.github.com/NeatMonster/451484af62d1aab712248c69d005e82b) for the processor-specific documentation, but that also has been scrapped.
